apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-world-web
    keel.sh/policy: force
    keel.sh/trigger: poll
    keel.sh/match-tag: "true" 
  annotations:
    keel.sh/pollSchedule: "@every 10m"
  name: hello-world-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-web
  strategy: {}
  template:
    metadata:
      labels:
        app: hello-world-web
    spec:
      containers:
      - image: gcr.io/gcr-test-223818/hello-world:latest
        name: hello-world-web
        resources: {}
        
status: {}